### ISSUE TITLE
How to process / confirm a shipment?

### ISSUE THREAD

**Issue by klaaskox** [picqer/bol-plaza-php-client#8]
When I try to ship an order (processShipment) it returns a BolPlazaProcessStatus that says it's pending and I need to confirm the shipment:

[id] => #####
[sellerId] => #####
[entityId] => #####
[eventType] => CONFIRM_SHIPMENT
[description] => Confirm shipment for order item #####.
[status] => PENDING
[errorMessage] =>
[createTimestamp] => 2017-08-17T11:23:54.000+02:00

How can I confirm this?
Thanks!

**Comment by mvdpanne** [comment]
Hi Klaas,

If I'm not mistaken the "Confirm shipment for order item #####" message refers to the task you're trying to carry out. The ProcessStatus entity describes the current status of this task.

So, just after requesting to ship an orderItem, the Plaza API returns this ProcessStatus object that tells you that the task is _PENDING_. This just means that Bol.com has not processed this shipment yet. You can request this ProcessStatus again at some point in the future to check whether the task has been completed. This can be done using the _ProcessStatus_ endpoint and the **id** field in the ProcessStatus object that has been returned to you.

At some point you will see that this task was completed, and the **status** field will contain _SUCCESS_ or _FAILURE_, indicating whether the task was successfully completed or not.

Hopefully this helps!

Link to the Shipments documentation: https://developers.bol.com/shipments-v2/
Link to the ProcessStatus documentation: https://developers.bol.com/resource-endpoints/process-status-v2/

**Comment by klaaskox** [comment]
Hi Maikel,
Thanks for your reply!
It looks like the shipment isn't completed after 15 minutes, so I'm missing something else.

This is how I try to process a shipment:

```
$shipment = new Picqer\BolPlazaClient\Entities\BolPlazaShipmentRequest();
$shipment->OrderItemId = $bolOrderId;
$shipment->ShipmentReference = date('Y-m-d H:i:s');
$shipment->DateTime = date('Y-m-d\TH:i:s');
$shipment->ExpectedDeliveryDate = date('Y-m-d\TH:i:s', strtotime('+1 day'));
$transport = new Picqer\BolPlazaClient\Entities\BolPlazaTransport();
$transport->TransporterCode = 'TNT_BRIEF'; 
$transport->TrackAndTrace = $order->getProperty('next_shipping_barcode');
$shipment->Transport = $transport;
$client = new Picqer\BolPlazaClient\BolPlazaClient($publickey, $privatekey);
$result = $client->processShipment($shipment);
```

In the BolPlazaClientTest.php examples I see this line of code:
`$this->assertEquals($result->eventType, 'CONFIRM_SHIPMENT');`

Do I need this? Can you tell me what this line of code does?

**Comment by mvdpanne** [comment]
Hi Klaas,

I'm actually not sure how long it normally takes for Bol.com to process your shipment. The documentation only says 'as soon as possible', and unfortunately I have no personal experience with sending shipments like this. But, if after 15 minutes it still displays 'PENDING', then you probably just have to wait longer, because it is not one of the final statuses ('SUCCESS' or 'FAILURE').

At some point one of those two statuses should be visible, and then you know the shipment was processed (and as a result, it has succeeded, or failed). The code you use for sending a shipment request seems fine to me. The fact that you get ProcessStatus objects back also indicates the code is fine.

The line of code from the (unit) tests file is just a way of checking whether the endpoint does what it is expected to do. The eventType describes what kind of action you're trying to carry out/request. In the test file it is tested whether it's possible to request a shipment, and the result of the request is checked by making sure the eventType of the ProcessStatus object is as expected. In the case of a shipment request, the eventType should be equal to 'CONFIRM_SHIPMENT'.

There's no need to assert anything in your own code, though, as it's a construct mainly used for testing (or debugging).

**Comment by casperbakker** [comment]
Hi Klaas,

We are using the same calls as you do in your example, so there is no information missing there. I don't know how long that processing takes usually, but as @mvdpanne says: just wait a little longer.

Otherwise you could contact Bol.com at https://developers.bol.com/documentatie/plaza-api/contactformulier/ to verify why shipments are taking so long to create.

**Comment by klaaskox** [comment]
Maikel, Casper, thanks!
The shipment hasn't been completed yet (> 4 hours), so I'll try to contact Bol.com.

@casperbakker what value do you post for the ExpectedDeliveryDate? As you can see I set it to 1 day in the future (it takes 1 day before a package gets delivered to the customer). I think that is how I should use this value? When I manually process a shipment there is no need to enter this value.

**Comment by Reemface** [comment]
Hi Klaas,

I support the awnsers from casperbakker and mvdpanne.
I've dealt the same problem as you.

The ExpectedDeliveryDate i sent is:
`date('Y-m-d', strtotime('+1 day', time())).'T12:00:00+01:00'`

I save the [id] from the response and poll this to 'rest/process-status/v2' with a 5 minutes interval and keep doing this until they give me a success or failure, like mvdpanne said.

I will try to log the delay for you for the next orders.

**Comment by casperbakker** [comment]
We also just give the date of tomorrow:

```php
$tomorrow = Carbon::tomorrow();
$shipmentRequest->ExpectedDeliveryDate = $tomorrow->toDateString() . 'T' . $tomorrow->toTimeString();
```

**Comment by klaaskox** [comment]
Forgot to close this; problem solved with the ExpectedDeliveryDate fix!
